server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/iam/**

      default-filters:
        - name: DedupeResponseHeader
          args:
            Access-Control-Allow-Origin: RETAIN_FIRST
            Access-Control-Allow-Credentials: RETAIN_FIRST

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

springdoc:
  swagger-ui:
    enabled: true
    path: /
    urls:
      - name: IAM Service
        url: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG