server:
  port: 8080

spring:
  application:
    name: api-gateway

  boot:
    admin:
      client:
        url: http://localhost:9090

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/iam/**

        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/users/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profiles/**

        - id: reviews-service
          uri: lb://reviews-service
          predicates:
            - Path=/api/v1/reviews/**

        - id: task-events
          uri: lb://task-event-service
          predicates:
            - Path=/api/v1/events/**

        - id: task-tasks
          uri: lb://task-event-service
          predicates:
            - Path=/api/v1/tasks/**

        - id: subscription-plans
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/plans/**

        - id: subscription-subscription
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/subscription/**

        - id: subscription-payment-method
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/payment-method/**

        - id: event-quote-service
          uri: lb://event-quote-service
          predicates:
            - Path= /api/v1/quotes/**

        - id: event-quote-service
          uri: lb://event-quote-service
          predicates:
            - Path= /api/v1/social-events/**
             
        - id: event-quote-service
          uri: lb://event-quote-service
          predicates:
            - Path= /api/v1/customers/**

        - id: event-quote-service
          uri: lb://event-quote-service
          predicates:
            - Path= /api/v1/organizers/**

      default-filters:
        - name: DedupeResponseHeader
          args:
            Access-Control-Allow-Origin: RETAIN_FIRST
            Access-Control-Allow-Credentials: RETAIN_FIRST

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

authorization:
  jwt:
    secret: 14db3b405fd39d8a7434ea25d19e80eba402da04a4807ffa95114e92a140dd1c

springdoc:
  swagger-ui:
    enabled: true
    path: /
    urls:
      - name: IAM Service
        url: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG